### ISSUE TITLE
Makes the recipes of planks invalid.

### ISSUE THREAD

**Issue by Sigmenzzz** [matthewperiut/hotkettles#1]
Game version Forge 1.20.1.
Other mods only include Architectury API.
![屏幕截图 2024-12-03 110859](https://github.com/user-attachments/assets/1832f006-38ed-4682-a942-7ccb280dd5b7)

**Comment by matthewperiut** [comment]
Fixed in the latest version, thanks for the report, super jank code of mine was left behind and i forgot about it
